<<<<<<< HEAD
=======
DROP TABLE hk_chains CASCADE CONSTRAINTS;
DROP TABLE hk_chain_codes CASCADE CONSTRAINTS;

>>>>>>> b65c320 (Initial commit)
CREATE TABLE hk_chains (
    chain_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    chain_name VARCHAR2(100) NOT NULL,
    address VARCHAR2(200) NOT NULL,
    phone VARCHAR2(20),
    description CLOB,
    image_path VARCHAR2(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM hk_chains;

-- 1. 가맹점 테스트 데이터 추가
INSERT INTO hk_chains (chain_name, address, phone, description, image_path) 
VALUES ('헬킹 강남점', '서울시 강남구 테헤란로 123', '02-1234-5678', '강남 최대 규모의 헬스장입니다. 최신 운동기구와 전문 트레이너가 상주하고 있습니다.', 'gym1.jpg');

INSERT INTO hk_chains (chain_name, address, phone, description, image_path) 
VALUES ('헬킹 홍대점', '서울시 마포구 홍익로 456', '02-2345-6789', '젊은 분위기의 트렌디한 피트니스 센터입니다. 다양한 그룹 수업을 제공합니다.', 'gym2.jpg');

INSERT INTO hk_chains (chain_name, address, phone, description, image_path) 
VALUES ('헬킹 잠실점', '서울시 송파구 잠실동 789', '02-3456-7890', '넓은 공간과 수영장을 갖춘 종합 스포츠 센터입니다.', 'gym3.jpg');

INSERT INTO hk_chains (chain_name, address, phone, description, image_path) 
VALUES ('헬킹 부산점', '부산시 해운대구 해운대로 321', '051-1111-2222', '바다뷰를 감상하며 운동할 수 있는 특별한 공간입니다.', 'gym4.jpg');

INSERT INTO hk_chains (chain_name, address, phone, description, image_path) 
VALUES ('헬킹 대구점', '대구시 수성구 범어동 654', '053-3333-4444', '대구 지역 최고의 시설을 자랑하는 프리미엄 헬스장입니다.', 'gym5.jpg');

<<<<<<< HEAD
=======
INSERT INTO hk_chains (chain_name, address, phone, description, image_path) 
VALUES ('헬킹 동래점', '부산시 동래구 충렬사로 84', '053-3333-2222', '동래 지역 최고의 시설을 자랑하는 프리미엄 헬스장입니다.', 'gym6.jpg');

>>>>>>> b65c320 (Initial commit)
CREATE TABLE hk_chain_codes (
    chain_num NUMBER PRIMARY KEY,
    chain_code VARCHAR2(4) NOT NULL UNIQUE,
    is_active CHAR(1) DEFAULT 'Y',
    FOREIGN KEY (chain_num) REFERENCES hk_chains(chain_num)
);

<<<<<<< HEAD
=======
SELECT * FROM hk_chains;
SELECT * FROM hk_chain_codes WHERE chain_code = 'GN01';

SELECT * FROM hk_chain_codes WHERE chain_num = 2;

>>>>>>> b65c320 (Initial commit)
-- 2. 체인 코드 데이터 추가 (chain_num은 실제 생성된 값으로 조정 필요)
INSERT INTO hk_chain_codes (chain_num, chain_code, is_active) VALUES (1, 'GN01', 'Y');
INSERT INTO hk_chain_codes (chain_num, chain_code, is_active) VALUES (2, 'HD01', 'Y');
INSERT INTO hk_chain_codes (chain_num, chain_code, is_active) VALUES (3, 'JS01', 'Y');
INSERT INTO hk_chain_codes (chain_num, chain_code, is_active) VALUES (4, 'BS01', 'Y');
INSERT INTO hk_chain_codes (chain_num, chain_code, is_active) VALUES (5, 'DG01', 'Y');
<<<<<<< HEAD

SELECT * FROM hk_chain_codes;

SELECT * FROM hk_chains WHERE ROWNUM <= 3;
=======
INSERT INTO hk_chain_codes (chain_num, chain_code, is_active) VALUES (21, 'DR01', 'Y');

SELECT * FROM hk_chain_codes;

SELECT * FROM hk_chains WHERE ROWNUM <= 3;

-- 기존 테이블에 위도/경도 컬럼 추가
ALTER TABLE hk_chains ADD (
    latitude NUMBER(10,8),  -- 위도 (-90 ~ 90)
    longitude NUMBER(11,8)  -- 경도 (-180 ~ 180)
);

-- 기존 데이터에 좌표 정보 업데이트
-- 실제 데이터 확인 후 chain_num 사용
UPDATE hk_chains SET latitude = 37.5013, longitude = 127.0393 WHERE chain_num = 1;
UPDATE hk_chains SET latitude = 37.5563, longitude = 126.9237 WHERE chain_num = 2;
UPDATE hk_chains SET latitude = 37.5133, longitude = 127.1028 WHERE chain_num = 3;
UPDATE hk_chains SET latitude = 35.1540, longitude = 129.1186 WHERE chain_num = 4;
UPDATE hk_chains SET latitude = 35.8580, longitude = 128.6320 WHERE chain_num = 5;
UPDATE hk_chains SET latitude = 35.207390, longitude = 129.070147 WHERE chain_num = 21;
COMMIT WORK;

-- 좌표 정보가 있는 가맹점만 조회하는 뷰 생성 (옵션)
CREATE OR REPLACE VIEW hk_chains_with_coords AS
SELECT * FROM hk_chains 
WHERE latitude IS NOT NULL AND longitude IS NOT NULL;

sql-- 기존 함수 삭제
DROP FUNCTION test_function;

-- 새로운 함수 생성
CREATE OR REPLACE FUNCTION calculate_distance(
    lat1 NUMBER, lng1 NUMBER, lat2 NUMBER, lng2 NUMBER
) RETURN NUMBER 
DETERMINISTIC
IS
    earth_radius NUMBER := 6371; -- 지구 반지름 (km)
    dlat NUMBER;
    dlng NUMBER;
    a NUMBER;
    c NUMBER;
    distance NUMBER;
BEGIN
    -- NULL 체크
    IF lat1 IS NULL OR lng1 IS NULL OR lat2 IS NULL OR lng2 IS NULL THEN
        RETURN NULL;
    END IF;
    
    -- 같은 위치인 경우
    IF lat1 = lat2 AND lng1 = lng2 THEN
        RETURN 0;
    END IF;
    
    -- Haversine 공식
    dlat := RADIANS(lat2 - lat1);
    dlng := RADIANS(lng2 - lng1);
    
    a := POWER(SIN(dlat/2), 2) + 
         COS(RADIANS(lat1)) * COS(RADIANS(lat2)) * 
         POWER(SIN(dlng/2), 2);
    
    c := 2 * ATAN2(SQRT(a), SQRT(1-a));
    distance := earth_radius * c;
    
    RETURN distance;
EXCEPTION
    WHEN OTHERS THEN
        RETURN NULL;
END calculate_distance;
/

-- 가장 단순한 함수로 먼저 테스트
CREATE OR REPLACE FUNCTION test_function
RETURN NUMBER
IS
BEGIN
    RETURN 100;
END;
/

-- 테스트
SELECT test_function() FROM dual;

SELECT object_name, object_type, status 
FROM user_objects 
WHERE object_name = 'CALCULATE_DISTANCE';

-- 테스트 쿼리: 특정 좌표에서 5km 이내 가맹점 찾기
-- 예시: 서울역 (37.5547, 126.9706) 기준
SELECT 
    chain_num,
    chain_name,
    address,
    latitude,
    longitude,
    ROUND(calculate_distance(37.5547, 126.9706, latitude, longitude), 2) as distance_km
FROM hk_chains 
WHERE latitude IS NOT NULL AND longitude IS NOT NULL
  AND calculate_distance(37.5547, 126.9706, latitude, longitude) <= 5
ORDER BY distance_km;

SELECT chain_num, chain_name FROM hk_chains;

COMMIT;

   SELECT * FROM hk_chains WHERE chain_num = 1;
   SELECT * FROM hk_chain_codes WHERE chain_code = 'GN01';
>>>>>>> b65c320 (Initial commit)
