-- 디자인바디 프로그램 테이블
CREATE TABLE hk_design_body_programs (
    program_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    program_name VARCHAR2(100) NOT NULL,
    program_type VARCHAR2(20) NOT NULL, -- 'DIET', 'MUSCLE', 'CARDIO', 'REHAB'
    difficulty VARCHAR2(20) NOT NULL,    -- 'BEGINNER', 'INTERMEDIATE', 'ADVANCED'
    duration NUMBER NOT NULL,            -- 프로그램 기간 (일)
    description CLOB NOT NULL,
    instructor VARCHAR2(50) NOT NULL,
    image_path VARCHAR2(200),
    price NUMBER DEFAULT 0,
    target_audience VARCHAR2(500),       -- 대상자
    equipment VARCHAR2(500),             -- 필요 장비
    schedule CLOB,                       -- 스케줄 정보
    is_active CHAR(1) DEFAULT 'Y',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 디자인바디 프로그램 신청 테이블
CREATE TABLE hk_design_body_enrollments (
    enroll_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_num NUMBER NOT NULL,
    program_num NUMBER NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE', -- 'ACTIVE', 'COMPLETED', 'CANCELLED', 'PAUSED'
    payment_id VARCHAR2(100),
    enroll_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num),
    FOREIGN KEY (program_num) REFERENCES hk_design_body_programs(program_num)
);

-- 초기 프로그램 데이터
INSERT INTO hk_design_body_programs (program_name, program_type, difficulty, duration, description, instructor, price, target_audience, equipment, schedule) 
VALUES ('30일 홈 다이어트', 'DIET', 'BEGINNER', 30, '집에서 할 수 있는 기본적인 다이어트 프로그램입니다.', '김다이어트', 49000, '다이어트 초보자, 집에서 운동하고 싶은 분', '운동매트', '주 5회, 1회 30분');

INSERT INTO hk_design_body_programs (program_name, program_type, difficulty, duration, description, instructor, price, target_audience, equipment, schedule) 
VALUES ('근력강화 12주 프로그램', 'MUSCLE', 'INTERMEDIATE', 84, '체계적인 근력 향상을 위한 중급자 프로그램입니다.', '박근육', 89000, '근력 향상을 원하는 중급자', '덤벨, 바벨', '주 4회, 1회 60분');

INSERT INTO hk_design_body_programs (program_name, program_type, difficulty, duration, description, instructor, price, target_audience, equipment, schedule) 
VALUES ('유산소 마스터 6주', 'CARDIO', 'BEGINNER', 42, '심폐지구력 향상을 위한 프로그램입니다.', '이유산소', 39000, '유산소 운동 입문자', '없음', '주 3회, 1회 45분');

COMMIT WORK;

SELECT program_num, program_name, program_type, difficulty 
FROM hk_design_body_programs;

SELECT * FROM hk_design_body_programs WHERE program_type = 'DIET';