-- 푸드다이어리 데이터베이스 스키마
DROP TABLE hk_user_foods CASCADE CONSTRAINTS;
DROP TABLE hk_user_favorite_foods CASCADE CONSTRAINTS;
DROP TABLE hk_food_reference_weights CASCADE CONSTRAINTS;
DROP TABLE hk_food_types CASCADE CONSTRAINTS;
DROP TABLE hk_user_profiles CASCADE CONSTRAINTS;

-- 음식 기본 정보 테이블
CREATE TABLE hk_food_types (
    food_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    food_name VARCHAR2(100) NOT NULL,
    category VARCHAR2(50) DEFAULT '기타',  -- '곡류', '채소류', '과일류', '육류', '유제품' 등
    calories_per_100g NUMBER(5,1) NOT NULL,     -- 소수점 1자리
    protein_per_100g NUMBER(5,1) DEFAULT 0,
    carbs_per_100g NUMBER(5,1) DEFAULT 0,
    fat_per_100g NUMBER(5,1) DEFAULT 0,
    is_active CHAR(1) DEFAULT 'Y',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 음식 참고 중량 정보 테이블
CREATE TABLE hk_food_reference_weights (
    reference_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    food_num NUMBER NOT NULL,
    reference_unit VARCHAR2(50) NOT NULL,       -- "1공기", "중간크기 1개", "1컵" 등
    weight_grams NUMBER(6,1) NOT NULL,          -- 소수점 1자리
    description VARCHAR2(200),                  -- 추가 설명
    FOREIGN KEY (food_num) REFERENCES hk_food_types(food_num) ON DELETE CASCADE
);

-- 사용자 신체정보 테이블 (선택적)
CREATE TABLE hk_user_profiles (
    user_num NUMBER PRIMARY KEY,
    gender VARCHAR2(10),                        -- 'M', 'F'
    age NUMBER(3),
    weight_kg NUMBER(5,1),                      -- 소수점 1자리
    height_cm NUMBER(5,1),                      -- 키 정보 추가
    target_calories NUMBER(4,0),                -- 목표 칼로리 (정수)
    activity_level VARCHAR2(20) DEFAULT 'MODERATE',  -- 'LOW', 'MODERATE', 'HIGH'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num) ON DELETE CASCADE
);

-- 즐겨찾기 음식 테이블
CREATE TABLE hk_user_favorite_foods (
    user_num NUMBER,
    food_num NUMBER,
    added_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_num, food_num),
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num) ON DELETE CASCADE,
    FOREIGN KEY (food_num) REFERENCES hk_food_types(food_num) ON DELETE CASCADE
);

-- 사용자 음식 섭취 기록 테이블
CREATE TABLE hk_user_foods (
    food_log_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_num NUMBER NOT NULL,
    food_num NUMBER NOT NULL,
    amount_grams NUMBER(8,1) NOT NULL,          -- 섭취량 (g, 소수점 1자리)
    calories_consumed NUMBER(6,0) NOT NULL,     -- 섭취 칼로리 (반올림된 정수)
    protein_consumed NUMBER(6,1),               -- 섭취 단백질 (g)
    carbs_consumed NUMBER(6,1),                 -- 섭취 탄수화물 (g)
    fat_consumed NUMBER(6,1),                   -- 섭취 지방 (g)
    meal_type VARCHAR2(20) DEFAULT '기타',       -- '아침', '점심', '저녁', '간식', '기타'
    record_date DATE DEFAULT SYSDATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num) ON DELETE CASCADE,
    FOREIGN KEY (food_num) REFERENCES hk_food_types(food_num) ON DELETE CASCADE
);

-- 인덱스 생성 (성능 최적화)
CREATE INDEX idx_user_foods_date ON hk_user_foods(user_num, record_date);
CREATE INDEX idx_user_foods_meal ON hk_user_foods(user_num, meal_type, record_date);
CREATE INDEX idx_food_types_name ON hk_food_types(food_name);
CREATE INDEX idx_food_types_category ON hk_food_types(category, is_active);

-- 기본 음식 데이터 삽입
INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('백미밥', '곡류', 130.0, 2.5, 29.0, 0.3);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('현미밥', '곡류', 112.0, 2.8, 22.9, 0.9);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('식빵', '곡류', 269.0, 8.5, 49.0, 4.2);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('라면', '곡류', 506.0, 10.3, 69.0, 20.0);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('배추김치', '채소류', 18.0, 2.0, 3.6, 0.2);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('상추', '채소류', 16.0, 1.4, 2.9, 0.1);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('토마토', '채소류', 20.0, 0.9, 4.0, 0.2);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('오이', '채소류', 12.0, 0.6, 2.2, 0.1);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('사과', '과일류', 54.0, 0.2, 14.0, 0.2);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('바나나', '과일류', 93.0, 1.2, 22.0, 0.2);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('오렌지', '과일류', 44.0, 1.0, 11.0, 0.2);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('삼겹살', '육류', 331.0, 17.4, 0.0, 28.6);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('닭가슴살', '육류', 165.0, 31.0, 0.0, 3.6);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('소고기(등심)', '육류', 291.0, 21.4, 0.0, 22.0);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('달걀', '육류', 155.0, 12.6, 0.7, 10.5);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('우유', '유제품', 67.0, 3.2, 4.8, 3.8);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('요구르트', '유제품', 62.0, 3.2, 4.9, 3.3);

INSERT INTO hk_food_types (food_name, category, calories_per_100g, protein_per_100g, carbs_per_100g, fat_per_100g) 
VALUES ('치즈', '유제품', 330.0, 25.0, 1.3, 25.2);

-- 참고 중량 데이터 삽입 (헬킹 체인점 형식)
INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (1, '1공기', 200.0, '일반적인 밥공기 기준');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (1, '1/2공기', 100.0, '다이어트용 반공기');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (1, '큰공기', 250.0, '큰 밥공기 기준');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (2, '1공기', 200.0, '일반적인 밥공기 기준');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (2, '1/2공기', 100.0, '다이어트용 반공기');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (3, '1장', 30.0, '일반 식빵 1장');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (3, '2장', 60.0, '아침식사용 2장');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (4, '1봉지', 120.0, '일반 라면 면 기준');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (5, '1접시', 100.0, '반찬용 1접시');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (6, '5장', 50.0, '쌈용 5장 정도');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (7, '중간크기 1개', 180.0, '일반 토마토 1개');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (8, '1개', 100.0, '일반 오이 1개');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (9, '중간크기 1개', 180.0, '일반 사과 1개');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (10, '중간크기 1개', 120.0, '일반 바나나 1개');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (11, '중간크기 1개', 150.0, '일반 오렌지 1개');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (12, '1인분', 100.0, '구이용 1인분');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (13, '1조각', 120.0, '구이용 1조각');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (14, '1인분', 150.0, '구이용 1인분');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (15, '1개', 60.0, '계란 1개');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (16, '1컵', 200.0, '일반 컵 기준');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (17, '1컵', 180.0, '플레인 요구르트');

INSERT INTO hk_food_reference_weights (food_num, reference_unit, weight_grams, description) 
VALUES (18, '1장', 20.0, '슬라이스 치즈 1장');

-- 샘플 사용자 프로필 데이터 (테스트용)
INSERT INTO hk_user_profiles (user_num, gender, age, weight_kg, height_cm, target_calories, activity_level) VALUES 
(1, 'M', 30, 75.0, 175.0, 2200, 'MODERATE');

-- 데이터 확인 쿼리
SELECT 
    f.food_name,
    f.category,
    f.calories_per_100g,
    r.reference_unit,
    r.weight_grams,
    ROUND((f.calories_per_100g * r.weight_grams / 100)) AS calories_per_unit
FROM hk_food_types f
LEFT JOIN hk_food_reference_weights r ON f.food_num = r.food_num
ORDER BY f.category, f.food_name, r.weight_grams;

SELECT food_log_num, food_num, meal_type, record_date, 
       TO_CHAR(record_date, 'YYYY-MM-DD HH24:MI:SS') as formatted_date,
       created_at
FROM hk_user_foods 
WHERE user_num = 1 
ORDER BY created_at DESC;

COMMIT WORK;