<<<<<<< HEAD
=======
DROP TABLE hk_qr_visits CASCADE CONSTRAINTS;

>>>>>>> b65c320 (Initial commit)
CREATE TABLE hk_qr_visits (
    visit_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_num NUMBER NOT NULL,
    chain_num NUMBER NOT NULL,
    visit_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    result VARCHAR2(20) NOT NULL,
    failure_reason VARCHAR2(200),
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num),
    FOREIGN KEY (chain_num) REFERENCES hk_chains(chain_num)
);

-- 테스트용 방문 기록 추가
INSERT INTO hk_qr_visits (user_num, chain_num, result, visit_time) 
VALUES (4, 1, 'SUCCESS', SYSDATE - 1);

INSERT INTO hk_qr_visits (user_num, chain_num, result, visit_time) 
VALUES (4, 2, 'SUCCESS', SYSDATE - 2);

INSERT INTO hk_qr_visits (user_num, chain_num, result, failure_reason, visit_time) 
VALUES (4, 3, 'FAILED', '패스권 만료', SYSDATE - 3);

<<<<<<< HEAD
COMMIT WORK;
=======
COMMIT WORK;

SELECT table_name FROM user_tables 
WHERE table_name IN ('HK_USERS', 'HK_CHAINS', 'HK_CHAIN_CODES', 'HK_PASSES', 'HK_USER_PASSES', 'HK_QR_VISITS');

SELECT user_num, user_id, username, email FROM hk_users WHERE user_num = 1;

SELECT c.chain_num, c.chain_name, cc.chain_code, cc.is_active 
FROM hk_chains c 
JOIN hk_chain_codes cc ON c.chain_num = cc.chain_num 
WHERE cc.chain_code = 'GN01';

SELECT up.user_pass_num, up.user_num, up.pass_num, up.status, 
       up.start_date, up.end_date, p.pass_name, u.username
FROM hk_user_passes up 
JOIN hk_passes p ON up.pass_num = p.pass_num 
JOIN hk_users u ON up.user_num = u.user_num 
WHERE up.user_num = 1 AND up.status = 'ACTIVE' AND up.end_date >= SYSDATE;

SELECT COUNT(*) as recent_visit_count
FROM hk_qr_visits v
JOIN hk_chains c ON v.chain_num = c.chain_num
JOIN hk_chain_codes cc ON c.chain_num = cc.chain_num
WHERE v.user_num = 1 
  AND cc.chain_code = 'GN01'
  AND v.visit_time >= (SYSDATE - INTERVAL '1' HOUR) 
  AND v.result = 'SUCCESS';
  
  
DELETE FROM hk_qr_visits WHERE user_num = 1 AND chain_num = 1;
COMMIT WORK;

SELECT v.visit_num, v.user_num, v.chain_num, v.result, 
       c.chain_name, c.address
FROM hk_qr_visits v 
LEFT JOIN hk_chains c ON v.chain_num = c.chain_num 
WHERE v.user_num = 1
ORDER BY v.visit_time DESC;

SELECT chain_num, chain_name FROM hk_chains;

SELECT DISTINCT v.chain_num, c.chain_name 
FROM hk_qr_visits v 
LEFT JOIN hk_chains c ON v.chain_num = c.chain_num 
WHERE v.user_num = 1;

SELECT DISTINCT chain_num FROM hk_qr_visits WHERE user_num = 1;
>>>>>>> b65c320 (Initial commit)
