CREATE TABLE hk_reviews (
    review_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_num NUMBER NOT NULL,
    chain_num NUMBER NOT NULL,
    rating NUMBER(2,1) NOT NULL,
    title VARCHAR2(100) NOT NULL,
    content CLOB NOT NULL,
    like_count NUMBER DEFAULT 0,
    dislike_count NUMBER DEFAULT 0,
    is_excellent CHAR(1) DEFAULT 'N',
    view_count NUMBER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num),
    FOREIGN KEY (chain_num) REFERENCES hk_chains(chain_num)
);

CREATE TABLE hk_review_comments (
    comment_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    review_num NUMBER NOT NULL,
    user_num NUMBER NOT NULL,
    content VARCHAR2(1000) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (review_num) REFERENCES hk_reviews(review_num),
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num)
);

CREATE TABLE hk_review_likes (
    like_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    review_num NUMBER NOT NULL,
    user_num NUMBER NOT NULL,
    like_type VARCHAR2(10) NOT NULL,
    FOREIGN KEY (review_num) REFERENCES hk_reviews(review_num),
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num)
);

<<<<<<< HEAD
SELECT * FROM hk_chains;

INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (3, 1, 4.5, '강남점 정말 좋아요!', '시설이 깨끗하고 트레이너분들이 정말 친절하시네요. 운동기구도 최신이라 만족스럽습니다. 특히 샤워실이 깔끔해서 좋아요.');

INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (3, 2, 4.0, '홍대점 분위기 최고', '젊은 분위기라서 운동하기 좋아요. 음악도 신나고 다른 회원분들도 열심히 해서 자극이 됩니다. 그룹수업 추천해요!');

INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (3, 1, 5.0, '완벽한 헬스장', '정말 완벽합니다! PT도 받고 있는데 트레이너님이 너무 전문적이에요. 3개월 다니면서 몸이 확실히 달라졌어요. 강추합니다!');

INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (3, 3, 4.2, '잠실점 수영장 굿', '헬스도 좋지만 수영장이 정말 좋아요. 물도 깨끗하고 레인도 충분해서 쾌적하게 수영할 수 있어요. 사우나도 만족스러워요.');

INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (3, 4, 4.8, '부산점 바다뷰 최고', '운동하면서 바다를 볼 수 있다니! 정말 힐링되는 운동이에요. 시설도 좋고 직원분들도 친절하셔서 기분 좋게 운동했습니다.');

INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (3, 2, 3.8, '홍대점 아쉬운 점', '전체적으로는 만족하지만 피크타임에 너무 붐벼서 기다리는 시간이 길어요. 좀 더 여유있게 운동하고 싶은데 아쉽네요.');

INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (3, 5, 4.6, '대구점 프리미엄 다운', '프리미엄이라는 이름에 걸맞게 시설이 정말 좋아요. 가격은 좀 있지만 그만한 값어치는 합니다. 운동 환경이 최고예요.');

INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (3, 1, 4.3, '강남점 2번째 후기', '처음 왔을 때보다 더 좋아진 것 같아요. 새로운 기구들도 들어오고 프로그램도 다양해졌네요. 계속 다닐 예정입니다.');
=======
-- 리뷰 이미지 테이블 생성
DROP TABLE hk_review_images CASCADE CONSTRAINTS;

CREATE TABLE hk_review_images (
    image_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    review_num NUMBER NOT NULL,
    image_path VARCHAR2(500) NOT NULL,
    original_name VARCHAR2(200) NOT NULL,
    image_order NUMBER DEFAULT 1,
    image_size NUMBER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (review_num) REFERENCES hk_reviews(review_num) ON DELETE CASCADE
);

-- 인덱스 생성
CREATE INDEX idx_review_images_review_num ON hk_review_images(review_num);
CREATE INDEX idx_review_images_order ON hk_review_images(review_num, image_order);

-- 가맹점 평점 컬럼 추가 (이미 있다면 생략)
ALTER TABLE hk_chains ADD (
    avg_rating NUMBER(3,2) DEFAULT 0,
    review_count NUMBER DEFAULT 0
);

-- 가맹점 평점 초기 계산 프로시저
CREATE OR REPLACE PROCEDURE UPDATE_CHAIN_RATINGS AS
BEGIN
    UPDATE hk_chains c SET (avg_rating, review_count) = (
        SELECT NVL(AVG(r.rating), 0), COUNT(r.review_num)
        FROM hk_reviews r
        WHERE r.chain_num = c.chain_num
    );
    COMMIT;
END;
/

-- 기존 데이터에 대한 평점 계산 실행
BEGIN
    UPDATE_CHAIN_RATINGS;
END;
/

-- 테스트용 이미지 데이터 (선택사항)
INSERT INTO hk_review_images (review_num, image_path, original_name, image_order) 
VALUES (21, '/upload/2024/12/17/s_abcd1234_sample1.jpg', 'sample_gym1.jpg', 1);

INSERT INTO hk_review_images (review_num, image_path, original_name, image_order) 
VALUES (21, '/upload/2024/12/17/s_abcd1234_sample2.jpg', 'sample_gym2.jpg', 2);

SELECT * FROM hk_review_images ORDER BY review_num, image_order;

SELECT * FROM hk_chains;

INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (1, 1, 4.5, '강남점 정말 좋아요!', '시설이 깨끗하고 트레이너분들이 정말 친절하시네요. 운동기구도 최신이라 만족스럽습니다. 특히 샤워실이 깔끔해서 좋아요.');

INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (1, 2, 4.0, '홍대점 분위기 최고', '젊은 분위기라서 운동하기 좋아요. 음악도 신나고 다른 회원분들도 열심히 해서 자극이 됩니다. 그룹수업 추천해요!');

INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (1, 1, 5.0, '완벽한 헬스장', '정말 완벽합니다! PT도 받고 있는데 트레이너님이 너무 전문적이에요. 3개월 다니면서 몸이 확실히 달라졌어요. 강추합니다!');

INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (1, 3, 4.2, '잠실점 수영장 굿', '헬스도 좋지만 수영장이 정말 좋아요. 물도 깨끗하고 레인도 충분해서 쾌적하게 수영할 수 있어요. 사우나도 만족스러워요.');

INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (1, 4, 4.8, '부산점 바다뷰 최고', '운동하면서 바다를 볼 수 있다니! 정말 힐링되는 운동이에요. 시설도 좋고 직원분들도 친절하셔서 기분 좋게 운동했습니다.');

INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (1, 2, 3.8, '홍대점 아쉬운 점', '전체적으로는 만족하지만 피크타임에 너무 붐벼서 기다리는 시간이 길어요. 좀 더 여유있게 운동하고 싶은데 아쉽네요.');

INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (1, 5, 4.6, '대구점 프리미엄 다운', '프리미엄이라는 이름에 걸맞게 시설이 정말 좋아요. 가격은 좀 있지만 그만한 값어치는 합니다. 운동 환경이 최고예요.');

INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (1, 1, 4.3, '강남점 2번째 후기', '처음 왔을 때보다 더 좋아진 것 같아요. 새로운 기구들도 들어오고 프로그램도 다양해졌네요. 계속 다닐 예정입니다.');
>>>>>>> b65c320 (Initial commit)


-- 리뷰 테이블 확인
SELECT * FROM hk_reviews;

-- 사용자 테이블 확인  
SELECT * FROM hk_users;

-- 가맹점 테이블 확인
SELECT * FROM hk_chains;

SELECT * FROM hk_reviews ORDER BY created_at DESC;
SELECT COUNT(*) FROM hk_reviews;

<<<<<<< HEAD
INSERT INTO hk_reviews (user_num, chain_num, rating, title, content) 
VALUES (4, 1, 4.5, '직접 삽입 테스트', '데이터베이스 직접 삽입 테스트입니다.');
=======
UPDATE hk_reviews SET like_count = 14, dislike_count = 2, view_count = 45 WHERE review_num = 21;  -- 총 6개 (우수리뷰)
UPDATE hk_reviews SET like_count = 14, dislike_count = 2, view_count = 38 WHERE review_num = 22;  -- 총 5개 (우수리뷰)  

-- 먼저 리뷰가 실제로 존재하는지 확인
SELECT review_num, title, like_count, dislike_count, view_count 
FROM hk_reviews 
WHERE review_num = 21;

SELECT review_num;

>>>>>>> b65c320 (Initial commit)

COMMIT WORK;
