-- 헬킹 피트니스 고객지원 시스템 테이블 생성

-- 1. FAQ 테이블
CREATE TABLE hk_faq (
    faq_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by NUMBER NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE',
    view_count NUMBER DEFAULT 0,
    CONSTRAINT fk_faq_created_by FOREIGN KEY (created_by) REFERENCES hk_users(user_num)
);

SELECT * FROM hk_inquiry;

-- 2. 문의사항 테이블 (통합형 - 답변도 같은 테이블에 저장)
CREATE TABLE hk_inquiry (
    inquiry_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    parent_num NUMBER, -- 답글의 경우 원글 번호
    title VARCHAR2(200) NOT NULL,
    content CLOB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by NUMBER NOT NULL,
    status VARCHAR2(20) DEFAULT 'ACTIVE', -- ACTIVE, COMPLETED, DELETED
    is_private CHAR(1) DEFAULT 'Y', -- 비공개 여부
    has_attachment CHAR(1) DEFAULT 'N', -- 첨부파일 여부
    view_count NUMBER DEFAULT 0,
    CONSTRAINT fk_inquiry_created_by FOREIGN KEY (created_by) REFERENCES hk_users(user_num),
    CONSTRAINT fk_inquiry_parent FOREIGN KEY (parent_num) REFERENCES hk_inquiry(inquiry_num)
);

-- 3. 문의사항 첨부파일 테이블
CREATE TABLE hk_inquiry_attachment (
    attachment_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    inquiry_num NUMBER NOT NULL,
    original_filename VARCHAR2(255) NOT NULL,
    saved_filename VARCHAR2(255) NOT NULL,
    file_size NUMBER,
    file_path VARCHAR2(500),
    upload_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attachment_inquiry FOREIGN KEY (inquiry_num) REFERENCES hk_inquiry(inquiry_num) ON DELETE CASCADE
);

-- 4. 상담예약 테이블
CREATE TABLE hk_consultation (
    consultation_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_num NUMBER NOT NULL,
    consultation_date DATE NOT NULL,
    consultation_time VARCHAR2(5) NOT NULL, -- '10:00', '11:00' 형식
    name VARCHAR2(50) NOT NULL,
    phone VARCHAR2(20) NOT NULL,
    email VARCHAR2(100),
    content CLOB,
    status VARCHAR2(20) DEFAULT 'CONFIRMED', -- CONFIRMED, CANCELLED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_consultation_user FOREIGN KEY (user_num) REFERENCES hk_users(user_num),
    CONSTRAINT uk_consultation_datetime UNIQUE (consultation_date, consultation_time)
);

SELECT * FROM hk_consultation;

-- 5. 인덱스 생성
CREATE INDEX idx_faq_status ON hk_faq(status);
CREATE INDEX idx_faq_created_at ON hk_faq(created_at DESC);

CREATE INDEX idx_inquiry_parent ON hk_inquiry(parent_num);
CREATE INDEX idx_inquiry_status ON hk_inquiry(status);
CREATE INDEX idx_inquiry_created_at ON hk_inquiry(created_at DESC);
CREATE INDEX idx_inquiry_created_by ON hk_inquiry(created_by);

CREATE INDEX idx_consultation_date ON hk_consultation(consultation_date);
CREATE INDEX idx_consultation_user ON hk_consultation(user_num);
CREATE INDEX idx_consultation_status ON hk_consultation(status);

-- 6. 샘플 FAQ 데이터 삽입 (관리자 계정으로)
INSERT INTO hk_faq (title, content, created_by) VALUES 
('헬킹영수증 또는 신용카드 매출전표는 어떻게 받나요?', 
'상품을 구매하면 영수증/매출전표는 자동으로 발급됩니다. 단, PC 웹사이트에서는 개별 확인, 앱과 확인, 출력까지 모두 가능하나, 모바일에서는 각 주문 개별로만 할 수 있습니다.

• 대금 결제 후 (대금 송금 후) 24시간 이후부터 영수증 조회 및 출력이 가능합니다.
• 직구 상품은 판매자가 해외에 사업장을 가지고 있어 해외의 법령 적용받아 현금영수증을 발행하지 않습니다.

영수증 확인 및 출력하기 (클릭)

이마트몰 확인하기 (클릭)

현금영수증 신청하기 (클릭)

현금영수증 소득공제 혜택을 위한 정보 (클릭)', 
(SELECT user_num FROM hk_users WHERE user_id = 'aqunasl22'));

INSERT INTO hk_faq (title, content, created_by) VALUES 
('예시예시', 
'예시', 
(SELECT user_num FROM hk_users WHERE user_id = 'aqunasl22'));

INSERT INTO hk_faq (title, content, created_by) VALUES 
('[베송일정] 주문한 상품을 언제 받을 수 있나요?', 
'[베송일정] 주문한 상품을 언제 받습니다요?', 
(SELECT user_num FROM hk_users WHERE user_id = 'aqunasl22'));

INSERT INTO hk_faq (title, content, created_by) VALUES 
('[교환/반품] 상품을 교환/반품하고 싶어요', 
'교환/반품은 상품 수령 후 7일 이내에 신청해주세요.', 
(SELECT user_num FROM hk_users WHERE user_id = 'aqunasl22'));

INSERT INTO hk_faq (title, content, created_by) VALUES 
('[취소 멜님] 취소 멜님을 해지하고 싶어요', 
'취소는 마이페이지에서 직접 처리하실 수 있습니다.', 
(SELECT user_num FROM hk_users WHERE user_id = 'aqunasl22'));

-- 7. 커밋
COMMIT WORK;

-- 8. 테이블 확인 쿼리들
SELECT COUNT(*) as faq_count FROM hk_faq;
SELECT COUNT(*) as inquiry_count FROM hk_inquiry;
SELECT COUNT(*) as consultation_count FROM hk_consultation;

-- 상담 예약 가능 시간 확인 예시 쿼리
SELECT consultation_time, COUNT(*) as booking_count 
FROM hk_consultation 
WHERE consultation_date = DATE '2024-01-15' 
AND status = 'CONFIRMED'
GROUP BY consultation_time
ORDER BY consultation_time;

SELECT * FROM hk_inquiry_attachment WHERE attachment_num = 1;

SELECT 
    attachment_num,
    inquiry_num,
    original_filename,
    saved_filename,
    file_path,
    file_size
FROM hk_inquiry_attachment 
WHERE attachment_num = 1;

-- 공휴일 테이블 생성
CREATE TABLE hk_holidays (
    holiday_date DATE PRIMARY KEY,
    holiday_name VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 상담예약 시퀀스 생성
CREATE SEQUENCE hk_consultation_seq
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 2025년 공휴일 데이터
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2025-01-01', '신정');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2025-01-28', '설날연휴');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2025-01-29', '설날');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2025-01-30', '설날연휴');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2025-03-01', '삼일절');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2025-05-05', '어린이날');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2025-05-06', '대체공휴일');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2025-06-06', '현충일');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2025-08-15', '광복절');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2025-10-06', '추석연휴');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2025-10-07', '추석');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2025-10-08', '추석연휴');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2025-10-09', '한글날');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2025-12-25', '크리스마스');

-- 2026년 공휴일 데이터
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2026-01-01', '신정');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2026-02-16', '설날연휴');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2026-02-17', '설날');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2026-02-18', '설날연휴');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2026-03-01', '삼일절');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2026-05-05', '어린이날');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2026-05-25', '부처님오신날');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2026-06-06', '현충일');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2026-08-15', '광복절');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2026-09-24', '추석연휴');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2026-09-25', '추석');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2026-09-26', '추석연휴');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2026-10-03', '개천절');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2026-10-09', '한글날');
INSERT INTO hk_holidays (holiday_date, holiday_name) VALUES (DATE '2026-12-25', '크리스마스');

   SELECT COUNT(*) FROM hk_faq WHERE status = 'ACTIVE';
   SELECT COUNT(*) FROM hk_inquiry WHERE status != 'DELETED';

   
   SELECT f.faq_num, f.title, f.created_by, u.username 
   FROM hk_faq f 
   LEFT JOIN hk_users u ON f.created_by = u.user_num 
   WHERE f.status = 'ACTIVE';   
   
      SELECT created_by FROM hk_faq WHERE status = 'ACTIVE';
      
         SELECT user_num, username FROM hk_users 
   WHERE user_num IN (SELECT created_by FROM hk_faq WHERE status = 'ACTIVE');
   
   SELECT inquiry_num, title, content 
FROM hk_inquiry 
WHERE title LIKE '%<%' OR content LIKE '%<%';

COMMIT WORK;

COMMIT