<<<<<<< HEAD
DROP TABLE validation_user PURGE;

CREATE TABLE hk_users (
    user_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(50) UNIQUE NOT NULL,
    username VARCHAR2(50) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    phone VARCHAR2(20) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL, -- BCrypt 암호화
=======
-- 기존 테이블 백업 (필요시)
-- CREATE TABLE hk_users_backup AS SELECT * FROM hk_user;

-- 통합된 사용자 테이블 (기존 데이터 보존하며 컬럼 추가)
DROP TABLE hk_users CASCADE CONSTRAINTS;
DROP TABLE hk_user_auth CASCADE CONSTRAINTS;
DROP TABLE hk_social_users CASCADE CONSTRAINTS;

CREATE TABLE hk_users (
    user_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_id VARCHAR2(50) UNIQUE NOT NULL,        -- 로그인용 아이디
    username VARCHAR2(50) NOT NULL,              -- 닉네임  
    email VARCHAR2(100) UNIQUE NOT NULL,         -- 이메일 (분리)
    phone VARCHAR2(20) UNIQUE NOT NULL,
    password VARCHAR2(255) NOT NULL,             -- BCrypt 암호화 지원
>>>>>>> b65c320 (Initial commit)
    profile_image VARCHAR2(200) DEFAULT 'avatar1.png',
    birth_date DATE,
    gender VARCHAR2(10),
    join_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR2(20) DEFAULT 'ACTIVE'
);

<<<<<<< HEAD
SELECT * FROM hk_users;

=======
ALTER TABLE hk_users MODIFY phone NULL;
ALTER TABLE hk_users MODIFY email NULL;

UPDATE hk_users SET status = 'ACTIVE' WHERE user_num = 1;
COMMIT WORK;

ALTER TABLE hk_users ADD account_type VARCHAR2(10) DEFAULT 'REGULAR';

UPDATE hk_users SET account_type = 'SOCIAL' 
WHERE password LIKE 'SOCIAL_%';

ALTER TABLE hk_users MODIFY account_type NOT NULL;

ALTER TABLE hk_users MODIFY profile_image VARCHAR2(500);

SELECT * FROM hk_users;

COMMIT WORK;

-- 사용자 인증 테이블 (SMS, 이메일 인증용)
>>>>>>> b65c320 (Initial commit)
CREATE TABLE hk_user_auth (
    auth_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_num NUMBER NOT NULL,
    auth_type VARCHAR2(20) NOT NULL, -- 'SMS', 'EMAIL'
    auth_code VARCHAR2(6) NOT NULL,
    expire_time TIMESTAMP NOT NULL,
    is_verified CHAR(1) DEFAULT 'N',
<<<<<<< HEAD
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num)
);

CREATE TABLE hk_social_users (
    social_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_num NUMBER NOT NULL,
    provider VARCHAR2(20) DEFAULT 'NAVER',
    social_user_id VARCHAR2(100) NOT NULL,
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num)
);
=======
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_num) REFERENCES hk_users(user_num)
);



ALTER TABLE hk_users ADD user_role VARCHAR2(20) DEFAULT 'USER';

UPDATE hk_users SET user_role = 'ADMIN' WHERE user_num IN ('1');

SELECT user_num, user_id, username, status FROM hk_users WHERE user_num = 1;

SELECT user_id, username, user_role FROM hk_users WHERE user_id IN ('aqunas22');

-- 소셜 로그인 테이블
CREATE TABLE hk_social_users (
    social_num NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    user_num NUMBER NOT NULL,
    provider VARCHAR2(20) NOT NULL,
    social_user_id VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_social_user FOREIGN KEY (user_num) REFERENCES hk_users(user_num) ON DELETE CASCADE,
    CONSTRAINT uk_social_account UNIQUE (provider, social_user_id)
);

SELECT user_num, user_id, username, email, account_type, status FROM hk_users WHERE email = 'aqunasl22@naver.com';

SELECT * FROM hk_social_users WHERE user_num IN (SELECT user_num FROM hk_users WHERE email = 'aqunasl22@naver.com');

-- 로그인 반복 시도 차단 IP 테이블
CREATE TABLE hk_ban_ip(
    ip VARCHAR2(50) PRIMARY KEY,
    cnt NUMBER DEFAULT 1,
    ban_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM hk_social_users;

SELECT user_num, user_id, username, email, phone, password, status 
FROM hk_users WHERE user_num = 53;

DELETE FROM hk_social_users WHERE user_num = 23;
DELETE FROM hk_users WHERE user_num = 23;

SELECT user_id, username, email FROM hk_users;
>>>>>>> b65c320 (Initial commit)
