jdbc.driver=oracle.jdbc.driver.OracleDriver
<<<<<<< HEAD
   jdbc.url=jdbc:oracle:thin:@localhost:1521/XE
   jdbc.username=DEVELOP_SPRING
   jdbc.password=12345
=======
jdbc.url=jdbc:oracle:thin:@localhost:1521/XE?characterEncoding=UTF-8&useUnicode=true
jdbc.username=develop_spring
jdbc.password=12345
>>>>>>> b65c320 (Initial commit)
